name: Build iOS Tweak

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Theos
        uses: beerpiss/theos-action@v1

      - name: Compile Package
        run: make package

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: FreeFireHackDemo-Package
          path: packages/*.deb
